### ISSUE TITLE
Production usage

### ISSUE THREAD

**Issue by avifatal** [tombatron/NRedisGraph#3]
Hi,
For now, I am using a nodejs microservice to communicate with redisgraph from c#, I'm thinking to switch to this library.

1. Is it production-ready?
2. Are you planning to continue and maintain it?

Thanks

**Comment by tombatron** [comment]
Hi there. 

Thanks for the questions, my answers are as follows:

1. I don't see why not. But as the license says, I make no warranties or guarantees. 

2. When time permits, sure. 

Thanks again!

Tom
