### ISSUE TITLE
Escaping query parameters

### ISSUE THREAD

**Issue by avifatal** [tombatron/NRedisGraph#4]
Hi,
I have some odd use-cases that I can't really put my finger on...
I am getting errors about un-escaped parameters, The bellow function received an `object` and internally convert it to a dictionary.
I have attached a screenshot that previews the dictionary. 
ontop of that, I have some other use cases of emojis throwing the same errors, but I can really put my finger on it...
```
//success
services.RedisGraphClient.Execute("CREATE (a:Test {SomeString: $SomeString})", new { SomeString = "dsfdsfdss\"" });

//fails
services.RedisGraphClient.Execute("CREATE (a:Test {SomeString: $SomeString})", new { SomeString = "ds\" fdsfdss\"" });
//fails
services.RedisGraphClient.Execute("CREATE (a:Test {SomeString: $SomeString})", new { SomeString = "dsfdsfdss\"#" });
```
Thanks

![image](https://user-images.githubusercontent.com/12430740/87391508-905c3000-c5b3-11ea-8156-46024e7606ea.png)

**Comment by tombatron** [comment]
I think I've got a fix for (me) not properly escaping the quotes in the parameters there (new release shortly). 

I also tried to create a node with an emoji as a value and it crashed my Redis instance...

```
"GRAPH.QUERY" "whatever" "CYPHER SometString=\"\xe1\xbd\xa42\" CREATE (a:Test {SomeString: $SomeString})"
```

I think I'm going to open an issue for that on the RedisGraph tracker. :thinking:

**Comment by tombatron** [comment]
Version 1.2 of NRediSearch should be available shortly.
